-- 0001_initial_schema.sql
-- Esquema inicial Dinamo Rent ERP — dialecto Firebird 5.0
-- Extraído del .fdb de producción (ODS 13.1). Orden de creación respeta FKs.

-- ── CONFIGURACION ────────────────────────────────────────────────────────────
CREATE TABLE configuracion (
    clave  VARCHAR(100) NOT NULL PRIMARY KEY,
    valor  BLOB SUB_TYPE TEXT,
    tipo   VARCHAR(30)
);

-- ── USUARIOS ────────────────────────────────────────────────────────────────
CREATE TABLE usuarios (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              VARCHAR(50) NOT NULL,
    password              VARCHAR(255) NOT NULL,
    nombre                VARCHAR(100),
    rol                   VARCHAR(50),
    email                 VARCHAR(100),
    activo                SMALLINT NOT NULL DEFAULT 1,
    intentos_fallidos     INTEGER NOT NULL DEFAULT 0,
    debe_cambiar_password SMALLINT NOT NULL DEFAULT 0,
    ultimo_acceso         TIMESTAMP,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX ix_usuarios_username ON usuarios (username);

-- ── AUDITORIA ───────────────────────────────────────────────────────────────
CREATE TABLE auditoria (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario VARCHAR(50),
    accion  VARCHAR(100),
    mensaje BLOB SUB_TYPE TEXT,
    ip      VARCHAR(45),
    fecha   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_auditoria_usuario ON auditoria (usuario);
CREATE INDEX ix_auditoria_fecha ON auditoria (fecha);
CREATE INDEX ix_auditoria_usuario_fecha ON auditoria (usuario, fecha);

-- ── AUTOS ───────────────────────────────────────────────────────────────────
CREATE TABLE autos (
    placa                VARCHAR(20) NOT NULL PRIMARY KEY,
    marca                VARCHAR(80) NOT NULL DEFAULT '',
    modelo               VARCHAR(80) NOT NULL DEFAULT '',
    version              VARCHAR(80),
    color                VARCHAR(50),
    tipo                 VARCHAR(50) NOT NULL DEFAULT '',
    cilindraje           VARCHAR(30),
    transmision          VARCHAR(30),
    combustible          VARCHAR(30),
    no_motor             VARCHAR(80),
    no_chasis            VARCHAR(80),
    propietario          VARCHAR(150),
    estado               VARCHAR(30) NOT NULL DEFAULT 'Disponible',
    costo_fijo_mensual   DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    kilometraje          DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    ubicacion            VARCHAR(150),
    tipo_adquisicion     VARCHAR(30),
    proximo_aceite       INTEGER DEFAULT 0,
    proximo_frenos       INTEGER DEFAULT 0,
    vencimiento_soat     DATE,
    vencimiento_tecnico  DATE,
    vencimiento_extintor DATE,
    vencimiento_bateria  DATE,
    observaciones        BLOB SUB_TYPE TEXT,
    fecha_ingreso        DATE NOT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_autos_estado ON autos (estado);
CREATE INDEX ix_autos_tipo ON autos (tipo);
CREATE INDEX ix_autos_estado_tipo ON autos (estado, tipo);

-- ── CLIENTES ────────────────────────────────────────────────────────────────
CREATE TABLE clientes (
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_doc             VARCHAR(30),
    no_doc               VARCHAR(30),
    nombres              VARCHAR(100) NOT NULL DEFAULT '',
    apellidos            VARCHAR(100),
    nombre_completo      VARCHAR(200) NOT NULL DEFAULT '',
    celular              VARCHAR(255),
    celular2             VARCHAR(255),
    email                VARCHAR(255),
    ciudad               VARCHAR(100),
    estado_region        VARCHAR(100),
    pais                 VARCHAR(80),
    nacionalidad         VARCHAR(80),
    dir_residencia       VARCHAR(255),
    dir_temporal         VARCHAR(255),
    hotel                VARCHAR(150),
    habitacion           VARCHAR(30),
    no_licencia          VARCHAR(255),
    tipo_licencia        VARCHAR(50),
    vencimiento_licencia DATE,
    estado               VARCHAR(30) NOT NULL DEFAULT 'Activo',
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX ix_clientes_no_doc ON clientes (no_doc);
CREATE INDEX ix_clientes_estado ON clientes (estado);
CREATE INDEX ix_clientes_nombre_completo ON clientes (nombre_completo);
CREATE INDEX ix_clientes_estado_nombre ON clientes (estado, nombre_completo);

-- ── RESERVAS ────────────────────────────────────────────────────────────────
CREATE TABLE reservas (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente          INTEGER REFERENCES clientes (id),
    nombre_cliente      VARCHAR(200),
    nacionalidad        VARCHAR(80),
    categoria_vehiculo  VARCHAR(50),
    placa_asignada      VARCHAR(20) REFERENCES autos (placa) ON DELETE SET NULL,
    fecha_recogida      DATE,
    hora_recogida       TIME,
    ubicacion_recogida  VARCHAR(200),
    fecha_retorno       DATE,
    hora_retorno        TIME,
    ubicacion_retorno   VARCHAR(200),
    dias_calculados     INTEGER DEFAULT 0,
    horas_extras        INTEGER DEFAULT 0,
    valor_dia           DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    valor_hora_adic     DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    abono               DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total               DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    observaciones       BLOB SUB_TYPE TEXT,
    estado              VARCHAR(30) NOT NULL DEFAULT 'Confirmada',
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_reservas_estado ON reservas (estado);
CREATE INDEX ix_reservas_estado_fecha ON reservas (estado, fecha_recogida);

-- ── RENTAS ──────────────────────────────────────────────────────────────────
CREATE TABLE rentas (
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa                  VARCHAR(20) REFERENCES autos (placa) ON UPDATE CASCADE,
    id_cliente             INTEGER REFERENCES clientes (id),
    nombre_cliente         VARCHAR(200),
    no_licencia            VARCHAR(50),
    nacionalidad           VARCHAR(80),
    fecha_recogida         DATE,
    hora_recogida          TIME,
    ubicacion_recogida     VARCHAR(200),
    fecha_retorno          DATE,
    hora_retorno           TIME,
    ubicacion_retorno      VARCHAR(200),
    dias_calculados        INTEGER DEFAULT 0,
    horas_extras           INTEGER DEFAULT 0,
    valor_dia              DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    valor_hora_extra       DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    valor_dia_extra        DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    costo_lavado           DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    costo_silla            DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    costo_retorno          DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    costo_domicilio        DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    costo_cables           DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    costo_inversor         DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    descuento              DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    subtotal               DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    impuestos              DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total                  DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    abono                  DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    saldo_pendiente        DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    estado                 VARCHAR(30) NOT NULL DEFAULT 'Activo',
    observaciones          BLOB SUB_TYPE TEXT,
    fecha_devolucion_real  DATE,
    hora_devolucion_real   TIME,
    km_final               VARCHAR(20),
    tanque_final           VARCHAR(20),
    km_salida              DOUBLE PRECISION NOT NULL DEFAULT 0.00,
    tanque_salida          VARCHAR(20) DEFAULT 'Lleno',
    id_reserva             INTEGER REFERENCES reservas (id) ON DELETE SET NULL,
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_rentas_estado ON rentas (estado);
CREATE INDEX idx_rentas_fechas ON rentas (fecha_recogida, fecha_retorno);
CREATE INDEX idx_rentas_estado_fecha_retorno ON rentas (estado, fecha_retorno);
CREATE INDEX idx_rentas_estado_placa ON rentas (estado, placa);
CREATE INDEX ix_rentas_placa ON rentas (placa);
CREATE INDEX ix_rentas_id_cliente ON rentas (id_cliente);

-- ── MANTENIMIENTO_VEHICULOS ─────────────────────────────────────────────────
CREATE TABLE mantenimiento_vehiculos (
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa                     VARCHAR(20) REFERENCES autos (placa) ON DELETE CASCADE,
    pieza_varias_tipo         VARCHAR(80),
    pieza_varias_fecha        DATE,
    pieza_varias_desc         VARCHAR(250),
    pieza_varias_obs          BLOB SUB_TYPE TEXT,
    cost_varios               DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    km_proximo_cambio_aceite  INTEGER DEFAULT 0,
    total_mantenimiento       DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_mantenimiento_vehiculos_placa ON mantenimiento_vehiculos (placa);
CREATE INDEX ix_mantenimiento_placa_fecha ON mantenimiento_vehiculos (placa, pieza_varias_fecha);

-- ── GASTOS ──────────────────────────────────────────────────────────────────
CREATE TABLE gastos (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa       VARCHAR(20) REFERENCES autos (placa) ON DELETE SET NULL,
    fecha       DATE NOT NULL,
    categoria   VARCHAR(50) NOT NULL,
    descripcion VARCHAR(200) NOT NULL,
    monto       DECIMAL(12,2) NOT NULL,
    comprobante VARCHAR(50),
    usuario     VARCHAR(50) DEFAULT 'Sistema',
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_gastos_placa ON gastos (placa);
CREATE INDEX ix_gastos_placa_fecha ON gastos (placa, fecha);
CREATE INDEX ix_gastos_categoria_fecha ON gastos (categoria, fecha);

-- ── COMPARENDOS ─────────────────────────────────────────────────────────────
CREATE TABLE comparendos (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa             VARCHAR(20) NOT NULL REFERENCES autos (placa) ON DELETE CASCADE,
    fecha_infraccion  DATE NOT NULL,
    hora_infraccion   TIME NOT NULL,
    monto             DECIMAL(12,2) NOT NULL DEFAULT 0,
    id_renta          INTEGER REFERENCES rentas (id) ON DELETE SET NULL,
    id_cliente        INTEGER REFERENCES clientes (id) ON DELETE SET NULL,
    estado            VARCHAR(20) DEFAULT 'Pendiente',
    observaciones     BLOB SUB_TYPE TEXT,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_comparendos_placa_fecha ON comparendos (placa, fecha_infraccion);

-- ── INSPECCIONES ────────────────────────────────────────────────────────────
CREATE TABLE inspecciones (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_renta            INTEGER NOT NULL REFERENCES rentas (id) ON DELETE CASCADE,
    tipo                VARCHAR(30) NOT NULL,
    fecha               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    kilometraje         DOUBLE PRECISION NOT NULL,
    nivel_gasolina      VARCHAR(20) NOT NULL,
    limpieza            VARCHAR(50) DEFAULT 'Limpio',
    tiene_repuesto      SMALLINT DEFAULT 1,
    tiene_gato_cruceta  SMALLINT DEFAULT 1,
    tiene_kit_carretera SMALLINT DEFAULT 1,
    tiene_documentos    SMALLINT DEFAULT 1,
    danos_carroceria    BLOB SUB_TYPE TEXT,
    observaciones       BLOB SUB_TYPE TEXT
);

-- ── PAGOS ───────────────────────────────────────────────────────────────────
CREATE TABLE pagos (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_renta      INTEGER NOT NULL REFERENCES rentas (id) ON DELETE CASCADE,
    fecha         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto         DECIMAL(12,2) NOT NULL,
    metodo_pago   VARCHAR(50) NOT NULL,
    concepto      VARCHAR(80) NOT NULL,
    observaciones BLOB SUB_TYPE TEXT,
    usuario       VARCHAR(50),
    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX ix_pagos_renta_fecha ON pagos (id_renta, fecha);
