-- 0002_indices_optimizacion.sql
-- Índices para optimizar las consultas del informe mensual y búsquedas por placa.
--
-- IDEMPOTENCIA: cada CREATE INDEX va guardado contra RDB$INDICES (EXECUTE
-- BLOCK + EXECUTE STATEMENT) para auto-reparar una instalación que quedó a
-- medias (índice creado pero migración sin registrar): al reintentar se omite
-- lo ya creado y se crea lo que falta.
--
-- Consolidado en 0011: IDX_MANTENIMIENTO_PLACA se eliminó de aquí (redundante
-- con el índice automático de la FK mantenimiento.placa → RDB$FOREIGN34).

-- Optimización de búsquedas por placa
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_RENTAS_PLACA')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_RENTAS_PLACA ON RENTAS (placa)';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_PAGOS_FECHA')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_PAGOS_FECHA ON PAGOS (fecha)';
END;

-- Optimización de informe mensual (rango de fechas)
EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_RENTAS_FECHA_RECOGIDA')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_RENTAS_FECHA_RECOGIDA ON RENTAS (fecha_recogida)';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_MANTENIMIENTO_FECHA')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_MANTENIMIENTO_FECHA ON MANTENIMIENTO_VEHICULOS (pieza_varias_fecha)';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_COMPARENDOS_FECHA')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_COMPARENDOS_FECHA ON COMPARENDOS (fecha_infraccion)';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_GASTOS_FECHA')) THEN
    EXECUTE STATEMENT 'CREATE INDEX IDX_GASTOS_FECHA ON GASTOS (fecha)';
END;
