-- 0024_extensiones_renta.sql
-- Tabla de historial de extensiones de rentas (horas o días extras agregados)
--
-- IDEMPOTENCIA: cada guard en su propio EXECUTE BLOCK (patrón 0001).

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = 'EXTENSIONES_RENTA')) THEN
    EXECUTE STATEMENT 'CREATE TABLE extensiones_renta (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        id_renta INTEGER NOT NULL,
        tipo VARCHAR(10) NOT NULL,
        cantidad INTEGER NOT NULL,
        valor_unitario DECIMAL(12,2) NOT NULL,
        valor_total DECIMAL(12,2) NOT NULL,
        observaciones VARCHAR(500),
        usuario VARCHAR(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT fk_extension_renta FOREIGN KEY (id_renta) REFERENCES rentas(id)
    )';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IDX_EXTENSIONES_RENTA_ID')) THEN
    EXECUTE STATEMENT 'CREATE INDEX idx_extensiones_renta_id ON extensiones_renta(id_renta)';
END;
