-- 0026: Agregar bandera "cobrar horas extras" a rentas.
-- Por defecto TRUE (compatibilidad con rentas existentes que ya cobraban HE).
-- Cuando el operador desmarca el checkbox, las horas extras no se cobran
-- aunque haya excedente de tiempo (cortesia al cliente).

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'RENTAS' AND RDB$FIELD_NAME = 'COBRAR_HORAS_EXTRA')) THEN
    EXECUTE STATEMENT 'ALTER TABLE RENTAS ADD COBRAR_HORAS_EXTRA SMALLINT DEFAULT 1';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'RENTAS' AND RDB$FIELD_NAME = 'COBRAR_HORAS_EXTRA')) THEN
    EXECUTE STATEMENT 'UPDATE RENTAS SET COBRAR_HORAS_EXTRA = 1 WHERE COBRAR_HORAS_EXTRA IS NULL';
END;
