-- 0027_soft_delete_entities.sql
-- Migra usuarios, reservas, clientes y autos de hard-delete a soft-delete.
-- Añade la columna DELETED_AT (TIMESTAMP, default NULL) a las 4 tablas
-- que aún usaban DELETE FROM, alineándolas con rentas, mantenimiento,
-- gastos y comparendos (ya migrados en 0006).
--
-- IDEMPOTENCIA: cada ALTER/INDEX va envuelto en EXECUTE BLOCK que
-- comprueba en el catálogo si el objeto ya existe (patrón de 0006).
-- Seguro de reintentar si una ejecución quedó a medias.

-- ── DELETED_AT column ──

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'USUARIOS' AND RDB$FIELD_NAME = 'DELETED_AT')) THEN
    EXECUTE STATEMENT 'ALTER TABLE usuarios ADD deleted_at TIMESTAMP';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'RESERVAS' AND RDB$FIELD_NAME = 'DELETED_AT')) THEN
    EXECUTE STATEMENT 'ALTER TABLE reservas ADD deleted_at TIMESTAMP';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'CLIENTES' AND RDB$FIELD_NAME = 'DELETED_AT')) THEN
    EXECUTE STATEMENT 'ALTER TABLE clientes ADD deleted_at TIMESTAMP';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS WHERE RDB$RELATION_NAME = 'AUTOS' AND RDB$FIELD_NAME = 'DELETED_AT')) THEN
    EXECUTE STATEMENT 'ALTER TABLE autos ADD deleted_at TIMESTAMP';
END;

-- ── Índices para filtrar registros activos ──

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IX_USUARIOS_DELETED')) THEN
    EXECUTE STATEMENT 'CREATE INDEX ix_usuarios_deleted ON usuarios (deleted_at)';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IX_RESERVAS_DELETED')) THEN
    EXECUTE STATEMENT 'CREATE INDEX ix_reservas_deleted ON reservas (deleted_at)';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IX_CLIENTES_DELETED')) THEN
    EXECUTE STATEMENT 'CREATE INDEX ix_clientes_deleted ON clientes (deleted_at)';
END;

EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(SELECT 1 FROM RDB$INDICES WHERE RDB$INDEX_NAME = 'IX_AUTOS_DELETED')) THEN
    EXECUTE STATEMENT 'CREATE INDEX ix_autos_deleted ON autos (deleted_at)';
END;
