#!/usr/bin/env python3
"""importar_autos_clientes.py — Importa las tablas AUTOS y CLIENTES desde un
dump SQL o desde un archivo Excel hacia la BD de DynaRent.

Caso de uso: el cliente tiene una copia de su BD (exportada a SQL) o los datos
están recopilados en una hoja de cálculo, y hay que llevarlos a la instalación.

Fuentes (elegir una):
  --sql ARCHIVO    Dump SQL con sentencias `INSERT INTO autos (...)` /
                   `INSERT INTO clientes (...)` (lo demás se ignora).
  --excel ARCHIVO  Libro con hojas "autos" y "clientes" (primera fila =
                   encabezados). Se aceptan encabezados en español o iguales a
                   la columna de la BD (sin tildes/mayúsculas).

Comportamiento (upsert):
  - AUTOS:    clave = placa (PK). Si existe, actualiza; si no, inserta.
  - CLIENTES: clave = no_doc (índice único). Si no_doc viene vacío se inserta
              siempre. Si existe, actualiza.
  Se salta el id de clientes (lo genera la BD, GENERATED BY DEFAULT AS IDENTITY).

PII:
  - Columnas sensibles de clientes: celular, celular2, email, dir_residencia,
    dir_temporal, no_licencia.
  - Desde SQL: si el valor ya viene cifrado (v1:...), se intenta un roundtrip
    con la clave del destino: si descifra, se re-cifra (garantiza coherencia);
    si no, se conserva tal cual con un aviso (asume misma clave). Si viene en
    claro, se cifra.
  - Desde Excel: siempre se cifra (el Excel trae datos en claro).

Por defecto es DRY-RUN (no escribe nada). Con --commit escribe en una
transacción (autos + clientes + auditoría IMPORTACION_DATOS) o revierte.

Uso:
  python scripts/importar_autos_clientes.py --sql dump.sql
  python scripts/importar_autos_clientes.py --sql dump.sql --commit
  python scripts/importar_autos_clientes.py --excel datos.xlsx
  python scripts/importar_autos_clientes.py --excel datos.xlsx --commit
  # opciones: --db RUTA --ini RUTA --hoja-autos HOJA --hoja-clientes HOJA --quiet
"""
import argparse
import base64
import configparser
import datetime
import hashlib
import os
import sys

os.environ["PATH"] = (
    r"D:\dinamo_rent_tr\src-tauri\resources\firebird"
    + os.pathsep
    + os.environ.get("PATH", "")
)

from firebird.driver import connect, driver_config  # noqa: E402
from cryptography.hazmat.primitives.ciphers.aead import AESGCM  # noqa: E402

driver_config.database_engine = "embedded"

# Columnas PII de clientes (mismo set que la app: core/crypto.rs PiiCipher).
COLS_PII = {
    "CELULAR", "CELULAR2", "EMAIL", "DIR_RESIDENCIA", "DIR_TEMPORAL", "NO_LICENCIA",
}

# Columnas por tabla (en el orden canónico de la BD).
COLS_AUTOS = [
    "PLACA", "MARCA", "MODELO", "VERSION", "COLOR", "TIPO", "CILINDRAJE",
    "TRANSMISION", "COMBUSTIBLE", "NO_MOTOR", "NO_CHASIS", "PROPIETARIO",
    "ESTADO", "COSTO_FIJO_MENSUAL", "KILOMETRAJE", "UBICACION",
    "TIPO_ADQUISICION", "PROXIMO_ACEITE", "PROXIMO_FRENOS", "VENCIMIENTO_SOAT",
    "VENCIMIENTO_TECNICO", "VENCIMIENTO_EXTINTOR", "VENCIMIENTO_BATERIA",
    "OBSERVACIONES", "FECHA_INGRESO",
]
COLS_CLIENTES = [
    "TIPO_DOC", "NO_DOC", "NOMBRES", "APELLIDOS", "NOMBRE_COMPLETO", "CELULAR",
    "CELULAR2", "EMAIL", "CIUDAD", "ESTADO_REGION", "PAIS", "NACIONALIDAD",
    "DIR_RESIDENCIA", "DIR_TEMPORAL", "HOTEL", "HABITACION", "NO_LICENCIA",
    "TIPO_LICENCIA", "VENCIMIENTO_LICENCIA", "ESTADO",
]

# Alias de encabezados de Excel (normalizados) -> columna de BD.
ALIASES = {
    "placa": "PLACA", "matricula": "PLACA",
    "marca": "MARCA", "modelo": "MODELO", "version": "VERSION", "color": "COLOR",
    "tipo": "TIPO", "cilindraje": "CILINDRAJE", "transmision": "TRANSMISION",
    "combustible": "COMBUSTIBLE", "no_motor": "NO_MOTOR", "n_motor": "NO_MOTOR",
    "motor": "NO_MOTOR", "no_chasis": "NO_CHASIS", "n_chasis": "NO_CHASIS",
    "chasis": "NO_CHASIS", "propietario": "PROPIETARIO", "estado": "ESTADO",
    "costo_fijo_mensual": "COSTO_FIJO_MENSUAL", "costofijo": "COSTO_FIJO_MENSUAL",
    "costo_fijo": "COSTO_FIJO_MENSUAL", "kilometraje": "KILOMETRAJE", "km": "KILOMETRAJE",
    "ubicacion": "UBICACION", "tipo_adquisicion": "TIPO_ADQUISICION",
    "adquisicion": "TIPO_ADQUISICION", "proximo_aceite": "PROXIMO_ACEITE",
    "prox_aceite": "PROXIMO_ACEITE", "proximo_frenos": "PROXIMO_FRENOS",
    "prox_frenos": "PROXIMO_FRENOS", "vencimiento_soat": "VENCIMIENTO_SOAT",
    "venc_soat": "VENCIMIENTO_SOAT", "soat": "VENCIMIENTO_SOAT",
    "vencimiento_tecnico": "VENCIMIENTO_TECNICO", "venc_tecnico": "VENCIMIENTO_TECNICO",
    "tecnico": "VENCIMIENTO_TECNICO", "vencimiento_extintor": "VENCIMIENTO_EXTINTOR",
    "venc_extintor": "VENCIMIENTO_EXTINTOR", "extintor": "VENCIMIENTO_EXTINTOR",
    "vencimiento_bateria": "VENCIMIENTO_BATERIA", "venc_bateria": "VENCIMIENTO_BATERIA",
    "bateria": "VENCIMIENTO_BATERIA", "observaciones": "OBSERVACIONES", "obs": "OBSERVACIONES",
    "fecha_ingreso": "FECHA_INGRESO", "fechaingreso": "FECHA_INGRESO",
    "tipo_doc": "TIPO_DOC", "tipodoc": "TIPO_DOC", "no_doc": "NO_DOC",
    "no_doc": "NO_DOC", "documento": "NO_DOC", "cedula": "NO_DOC", "c.c.": "NO_DOC",
    "nombres": "NOMBRES", "apellidos": "APELLIDOS", "nombre_completo": "NOMBRE_COMPLETO",
    "nombre": "NOMBRE_COMPLETO", "nombrecompleto": "NOMBRE_COMPLETO",
    "celular": "CELULAR", "telefono": "CELULAR", "celular2": "CELULAR2",
    "telefono2": "CELULAR2", "email": "EMAIL", "correo": "EMAIL",
    "ciudad": "CIUDAD", "estado_region": "ESTADO_REGION", "departamento": "ESTADO_REGION",
    "pais": "PAIS", "nacionalidad": "NACIONALIDAD", "dir_residencia": "DIR_RESIDENCIA",
    "direccion": "DIR_RESIDENCIA", "dir_temporal": "DIR_TEMPORAL",
    "hotel": "HOTEL", "habitacion": "HABITACION", "no_licencia": "NO_LICENCIA",
    "licencia": "NO_LICENCIA", "tipo_licencia": "TIPO_LICENCIA",
    "vencimiento_licencia": "VENCIMIENTO_LICENCIA", "venc_licencia": "VENCIMIENTO_LICENCIA",
}


def norm(s):
    """Normaliza un encabezado para el mapeo de aliases (sin tildes, mayúsculas)."""
    import unicodedata

    s = unicodedata.normalize("NFD", str(s or ""))
    s = "".join(c for c in s if unicodedata.category(c) != "Mn")
    return s.strip().lower().replace(" ", "_").replace("-", "_")


def derive_key(key_str):
    return hashlib.sha256(key_str.encode()).digest()


def encrypt(aes_key, plaintext):
    if not plaintext:
        return plaintext
    nonce = os.urandom(12)
    ct = AESGCM(aes_key).encrypt(nonce, plaintext.encode("utf-8"), None)
    return "v1:%s:%s" % (
        base64.b64encode(nonce).decode(),
        base64.b64encode(ct).decode(),
    )


def try_decrypt(aes_key, valor):
    """Descifra v1:... Devuelve (ok, texto)."""
    if not valor.startswith("v1:"):
        return True, valor
    try:
        body = valor[3:]
        nonce_b64, ct_b64 = body.split(":", 1)
        plain = AESGCM(aes_key).decrypt(
            base64.b64decode(nonce_b64), base64.b64decode(ct_b64), None
        )
        return True, plain.decode("utf-8")
    except Exception:  # noqa: BLE001
        return False, valor


def cifrar_pii(aes_key, valor, col):
    """Aplica la política PII de importación descrita en la cabecera."""
    if valor is None or valor == "":
        return None, ""
    if not isinstance(valor, str):
        valor = str(valor)
    if valor.startswith("v1:"):
        ok, claro = try_decrypt(aes_key, valor)
        if not ok:
            return valor, "v1-ajeno-conservado"
        # Roundtrip: re-cifrar con la clave destino (coherencia garantizada).
        return encrypt(aes_key, claro), ""
    return encrypt(aes_key, valor), ""


# ── Parser del dump SQL ────────────────────────────────────────────────────

def parse_sql_inserts(texto):
    """Extrae sentencias INSERT INTO <tabla> (...) VALUES (...) del texto.

    Devuelve [(tabla_mayus, {col: valor_python}, numero_linea)]. El parser
    respeta comillas simples ('') y paréntesis anidados dentro de los valores.
    Cualquier otra sentencia del dump (CREATE, ALTER, COMMIT...) se ignora.
    """
    resultado = []
    i = 0
    n = len(texto)
    while i < n:
        # Buscar "insert into" (case-insensitive)
        m = texto[i:].lower().find("insert into")
        if m == -1:
            break
        i += m + len("insert into")
        # Nombre de tabla
        j = i
        while j < n and texto[j] in " \t":
            j += 1
        tabla = ""
        while j < n and (texto[j].isalnum() or texto[j] in "_\"\""):
            if texto[j] not in '"':
                tabla += texto[j]
            j += 1
        tabla = tabla.strip().upper()
        if tabla not in ("AUTOS", "CLIENTES"):
            i = j
            continue
        # Columnas entre paréntesis
        j = skip_ws(texto, j)
        if j >= n or texto[j] != "(":
            i = j
            continue
        cols, j = read_parenthesis(texto, j)
        # VALUES
        j = skip_ws(texto, j)
        if texto[j:j + 6].lower() != "values":
            i = j
            continue
        j = skip_ws(texto, j + 6)
        if j >= n or texto[j] != "(":
            i = j
            continue
        vals, j = read_parenthesis(texto, j)
        cols = [c.strip().strip('"').upper() for c in cols]
        vals_parsed = [parse_sql_value(v.strip()) for v in vals]
        resultado.append((tabla, dict(zip(cols, vals_parsed)), None))
        i = j
    return resultado


def skip_ws(texto, i):
    n = len(texto)
    while i < n and texto[i] in " \t\r\n":
        i += 1
    return i


def read_parenthesis(texto, i):
    """Lee un paréntesis balanceado respetando comillas simples. Devuelve
    (lista_de_fragmentos_top_level, pos_tras_cierre)."""
    i += 1  # abrir (
    n = len(texto)
    frags = []
    cur = []
    depth = 1
    in_str = False
    while i < n:
        c = texto[i]
        if in_str:
            cur.append(c)
            if c == "'":
                if i + 1 < n and texto[i + 1] == "'":
                    cur.append("'")
                    i += 2
                    continue
                in_str = False
            i += 1
            continue
        if c == "'":
            in_str = True
            cur.append(c)
            i += 1
            continue
        if c == "(":
            depth += 1
            cur.append(c)
            i += 1
            continue
        if c == ")":
            depth -= 1
            if depth == 0:
                frags.append("".join(cur))
                return frags, i + 1
            cur.append(c)
            i += 1
            continue
        if c == "," and depth == 1:
            frags.append("".join(cur))
            cur = []
            i += 1
            continue
        cur.append(c)
        i += 1
    raise ValueError("paréntesis sin cerrar en el dump SQL")


def parse_sql_value(v):
    """Convierte un literal SQL a valor Python (None / str / num / fecha)."""
    if v == "":
        return None
    if v.upper() == "NULL":
        return None
    if v.startswith("'"):
        # string SQL: '' -> '
        s = v[1:-1].replace("''", "'")
        # Fechas/timestamps textuales de Firebird. SOLO con formato ISO estricto
        # (YYYY-MM-DD): desde Python 3.11+ fromisoformat acepta formatos compactos
        # (YYYYMMDD) y en 3.14 convierte '1052070892' -> date(1052,7,8), corrompiendo
        # columnas string numéricas como no_doc. Sin guiones -> nunca fecha.
        s2 = s.strip()
        if len(s2) == 10 and s2[4] == "-" and s2[7] == "-":
            try:
                return datetime.date.fromisoformat(s2)
            except ValueError:
                pass
        # Datetime solo si trae componente de hora (T o espacio + hora:min).
        s3 = s2.replace(" ", "T")
        if "T" in s3 and ":" in s3:
            try:
                return datetime.datetime.fromisoformat(s3)
            except ValueError:
                pass
        return s
    # Números
    try:
        if "." in v or "," in v.replace(",", "."):
            return float(v.replace(",", "."))
        return int(v)
    except ValueError:
        return v


# ── Lectura de Excel ───────────────────────────────────────────────────────

def leer_excel(path, hoja_autos, hoja_clientes):
    from openpyxl import load_workbook

    wb = load_workbook(path, data_only=True)
    tablas = {}
    for hoja, nombre_tabla in ((hoja_autos, "AUTOS"), (hoja_clientes, "CLIENTES")):
        ws = wb[hoja] if hoja else wb.worksheets[0]
        filas = list(ws.iter_rows(values_only=True))
        if not filas:
            tablas[nombre_tabla] = []
            continue
        headers = [norm(h) for h in filas[0]]
        map_col = {}
        for idx, h in enumerate(headers):
            if h in ALIASES:
                map_col[idx] = ALIASES[h]
        filas_out = []
        for row in filas[1:]:
            if row is None or all(c is None or str(c).strip() == "" for c in row):
                continue
            rec = {}
            for idx, col in map_col.items():
                val = row[idx] if idx < len(row) else None
                if val is not None and isinstance(val, str) and val.strip() == "":
                    val = None
                rec[col] = val
            filas_out.append(rec)
        tablas[nombre_tabla] = filas_out
    wb.close()
    return tablas


# ── Upsert ─────────────────────────────────────────────────────────────────

def upsert_autos(cur, filas, aes_key, reporte, quiet):
    cols = COLS_AUTOS
    for rec in filas:
        placa = (rec.get("PLACA") or "").strip().upper()
        if not placa:
            reporte["autos_saltados"] += 1
            if not quiet:
                print("  ! auto sin placa (saltado): %r" % (rec,))
            continue
        cur.execute("SELECT COUNT(*) FROM autos WHERE placa = ?", (placa,))
        existe = cur.fetchone()[0] > 0
        # Valores: solo columnas presentes; defaults para el resto.
        vals = []
        colset = []
        for c in cols:
            if c in rec and rec[c] is not None:
                colset.append(c)
                vals.append(rec[c])
        if "PLACA" not in colset:
            colset.append("PLACA")
            vals.append(placa)
        colset.append("UPDATED_AT")
        vals.append(datetime.datetime.now())
        if not existe:
            colset.append("CREATED_AT")
            vals.append(datetime.datetime.now())
        ph = ", ".join("?" for _ in colset)
        sql = "UPDATE OR INSERT INTO autos (%s) VALUES (%s) MATCHING (PLACA)" % (
            ", ".join(colset), ph,
        )
        cur.execute(sql, vals)
        if existe:
            reporte["autos_actualizados"] += 1
            if not quiet:
                print("  ~ auto %s actualizado" % placa)
        else:
            reporte["autos_nuevos"] += 1
            if not quiet:
                print("  + auto %s nuevo" % placa)


def upsert_clientes(cur, filas, aes_key, reporte, quiet):
    cols = COLS_CLIENTES
    for rec in filas:
        no_doc = (rec.get("NO_DOC") or "").strip()
        nombres = (rec.get("NOMBRES") or "").strip()
        nombre_completo = (rec.get("NOMBRE_COMPLETO") or "").strip()
        if not nombres and not nombre_completo:
            reporte["clientes_saltados"] += 1
            if not quiet:
                print("  ! cliente sin nombres (saltado): %r" % (rec,))
            continue
        if not nombre_completo:
            nombre_completo = "%s %s" % (
                nombres, (rec.get("APELLIDOS") or "").strip(),
            )
            nombre_completo = " ".join(nombre_completo.split())
            rec["NOMBRE_COMPLETO"] = nombre_completo
        # Cifrado PII
        avisos = {}
        for col in COLS_PII:
            if col in rec and rec[col] is not None:
                rec[col], nota = cifrar_pii(aes_key, rec[col], col)
                if nota:
                    avisos[col] = nota
        # Existe por no_doc?
        existe = False
        if no_doc:
            cur.execute("SELECT COUNT(*) FROM clientes WHERE no_doc = ?", (no_doc,))
            existe = cur.fetchone()[0] > 0
        vals = []
        colset = []
        for c in cols:
            if c in rec and rec[c] is not None:
                colset.append(c)
                vals.append(rec[c])
        colset.append("UPDATED_AT")
        vals.append(datetime.datetime.now())
        if not existe:
            colset.append("CREATED_AT")
            vals.append(datetime.datetime.now())
        if existe and no_doc:
            cur.execute(
                "UPDATE clientes SET %s WHERE no_doc = ?"
                % ", ".join("%s = ?" % c for c in colset),
                vals + [no_doc],
            )
            reporte["clientes_actualizados"] += 1
            if not quiet:
                print("  ~ cliente %s actualizado%s"
                      % (nombre_completo, avisos and " (%s)" % ",".join(avisos) or ""))
        else:
            ph = ", ".join("?" for _ in colset)
            cur.execute(
                "INSERT INTO clientes (%s) VALUES (%s)" % (", ".join(colset), ph),
                vals,
            )
            reporte["clientes_nuevos"] += 1
            if not quiet:
                print("  + cliente %s nuevo%s"
                      % (nombre_completo, avisos and " (%s)" % ",".join(avisos) or ""))


# ── main ───────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--sql", help="Dump SQL con INSERTs de autos/clientes")
    parser.add_argument("--excel", help="Libro Excel con hojas autos/clientes")
    parser.add_argument("--hoja-autos", default="autos")
    parser.add_argument("--hoja-clientes", default="clientes")
    parser.add_argument("--db", default=r"D:\dinamo_rent_tr\data\dinamo_rent_v3.fdb")
    parser.add_argument("--ini", default=r"D:\dinamo_rent_tr\data\config.ini")
    parser.add_argument("--commit", action="store_true", help="Escribe los cambios")
    parser.add_argument("--quiet", action="store_true", help="Solo resumen final")
    args = parser.parse_args()

    if not args.sql and not args.excel:
        print("ERROR: indica --sql ARCHIVO o --excel ARCHIVO.")
        sys.exit(2)
    if args.sql and args.excel:
        print("ERROR: elegir una sola fuente (--sql o --excel).")
        sys.exit(2)

    cfg = configparser.ConfigParser()
    if not os.path.exists(args.ini):
        print("ERROR: no existe %s" % args.ini)
        sys.exit(2)
    cfg.read(args.ini)
    user = cfg.get("database", "user", fallback="sysdba").strip()
    pwd = cfg.get("database", "password", fallback="").strip()
    key_str = cfg.get("security", "db_encryption_key", fallback="").strip()
    if not key_str:
        print("ERROR: db_encryption_key vacía en config.ini — no se puede cifrar PII.")
        sys.exit(2)
    aes_key = derive_key(key_str)

    # Cargar datos
    if args.sql:
        if not os.path.exists(args.sql):
            print("ERROR: no existe %s" % args.sql)
            sys.exit(2)
        with open(args.sql, encoding="utf-8", errors="replace") as f:
            texto = f.read()
        inserts = parse_sql_inserts(texto)
        filas = {"AUTOS": [], "CLIENTES": []}
        for tabla, rec, _ln in inserts:
            filas[tabla].append(rec)
        fuente = "SQL (%d INSERTs: %d autos, %d clientes)" % (
            len(inserts), len(filas["AUTOS"]), len(filas["CLIENTES"]),
        )
    else:
        filas = leer_excel(args.excel, args.hoja_autos, args.hoja_clientes)
        fuente = "Excel (%d autos, %d clientes)" % (
            len(filas["AUTOS"]), len(filas["CLIENTES"]),
        )

    print("== Fuente: %s" % fuente)
    print("== BD destino: %s" % args.db)
    print("== Modo: %s" % ("COMMIT" if args.commit else "DRY-RUN (no escribe)"))

    con = connect(args.db, user=user, password=pwd, charset="UTF8")
    con.autocommit = False
    cur = con.cursor()
    reporte = {
        "autos_nuevos": 0, "autos_actualizados": 0, "autos_saltados": 0,
        "clientes_nuevos": 0, "clientes_actualizados": 0, "clientes_saltados": 0,
    }
    try:
        print("-- autos --")
        upsert_autos(cur, filas["AUTOS"], aes_key, reporte, args.quiet)
        print("-- clientes --")
        upsert_clientes(cur, filas["CLIENTES"], aes_key, reporte, args.quiet)
        if args.commit:
            total = (
                reporte["autos_nuevos"] + reporte["autos_actualizados"]
                + reporte["clientes_nuevos"] + reporte["clientes_actualizados"]
            )
            if total > 0:
                cur.execute(
                    "INSERT INTO auditoria (usuario, accion, mensaje, ip, fecha) "
                    "VALUES (?, ?, ?, ?, CURRENT_TIMESTAMP)",
                    (
                        "sistema",
                        "IMPORTACION_DATOS",
                        "Importación desde %s: %d autos (nuevos %d, actualizados %d), "
                        "%d clientes (nuevos %d, actualizados %d)" % (
                            "SQL" if args.sql else "Excel",
                            reporte["autos_nuevos"] + reporte["autos_actualizados"],
                            reporte["autos_nuevos"], reporte["autos_actualizados"],
                            reporte["clientes_nuevos"] + reporte["clientes_actualizados"],
                            reporte["clientes_nuevos"], reporte["clientes_actualizados"],
                        ),
                        "local",
                    ),
                )
            con.commit()
            print("== COMMIT OK ==")
        else:
            con.rollback()
            print("== DRY-RUN: nada escrito. Re-ejecuta con --commit para aplicar. ==")
    except Exception as e:  # noqa: BLE001
        con.rollback()
        print("== ERROR: se revirtió la transacción — %s: %s" % (type(e).__name__, e))
        con.close()
        sys.exit(1)
    finally:
        con.close()

    print("\n=== Reporte ===")
    print("  autos:    nuevos %d · actualizados %d · saltados %d" % (
        reporte["autos_nuevos"], reporte["autos_actualizados"], reporte["autos_saltados"],
    ))
    print("  clientes: nuevos %d · actualizados %d · saltados %d" % (
        reporte["clientes_nuevos"], reporte["clientes_actualizados"],
        reporte["clientes_saltados"],
    ))


if __name__ == "__main__":
    main()
